// Auto-generated by upload_cloudinary.js
window.MEDIA = {
  "generated_at": "2026-02-26T12:28:09.534Z",
  "cloudinary_folder": "iloveyou",
  "images": [
    {
      "name": "1.avif",
      "local": "img/1.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108894/iloveyou/images/1.avif",
      "bytes": 42923,
      "size_mb": 0.04
    },
    {
      "name": "10.avif",
      "local": "img/10.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108898/iloveyou/images/10.avif",
      "bytes": 35036,
      "size_mb": 0.03
    },
    {
      "name": "100.avif",
      "local": "img/100.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108909/iloveyou/images/100.avif",
      "bytes": 85297,
      "size_mb": 0.08
    },
    {
      "name": "101.avif",
      "local": "img/101.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108922/iloveyou/images/101.avif",
      "bytes": 105439,
      "size_mb": 0.1
    },
    {
      "name": "102.avif",
      "local": "img/102.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108936/iloveyou/images/102.avif",
      "bytes": 96919,
      "size_mb": 0.09
    },
    {
      "name": "103.avif",
      "local": "img/103.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108944/iloveyou/images/103.avif",
      "bytes": 56992,
      "size_mb": 0.05
    },
    {
      "name": "104.avif",
      "local": "img/104.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108951/iloveyou/images/104.avif",
      "bytes": 53167,
      "size_mb": 0.05
    },
    {
      "name": "105.avif",
      "local": "img/105.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108965/iloveyou/images/105.avif",
      "bytes": 116880,
      "size_mb": 0.11
    },
    {
      "name": "106.avif",
      "local": "img/106.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108977/iloveyou/images/106.avif",
      "bytes": 99514,
      "size_mb": 0.09
    },
    {
      "name": "107.avif",
      "local": "img/107.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108989/iloveyou/images/107.avif",
      "bytes": 112702,
      "size_mb": 0.11
    },
    {
      "name": "108.avif",
      "local": "img/108.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108994/iloveyou/images/108.avif",
      "bytes": 29807,
      "size_mb": 0.03
    },
    {
      "name": "109.avif",
      "local": "img/109.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772108999/iloveyou/images/109.avif",
      "bytes": 17835,
      "size_mb": 0.02
    },
    {
      "name": "11.avif",
      "local": "img/11.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109003/iloveyou/images/11.avif",
      "bytes": 38507,
      "size_mb": 0.04
    },
    {
      "name": "110.avif",
      "local": "img/110.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109008/iloveyou/images/110.avif",
      "bytes": 17354,
      "size_mb": 0.02
    },
    {
      "name": "111.avif",
      "local": "img/111.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109013/iloveyou/images/111.avif",
      "bytes": 16481,
      "size_mb": 0.02
    },
    {
      "name": "112.avif",
      "local": "img/112.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109017/iloveyou/images/112.avif",
      "bytes": 13166,
      "size_mb": 0.01
    },
    {
      "name": "12.avif",
      "local": "img/12.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109021/iloveyou/images/12.avif",
      "bytes": 37595,
      "size_mb": 0.04
    },
    {
      "name": "13.avif",
      "local": "img/13.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109026/iloveyou/images/13.avif",
      "bytes": 51548,
      "size_mb": 0.05
    },
    {
      "name": "14.avif",
      "local": "img/14.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109030/iloveyou/images/14.avif",
      "bytes": 56829,
      "size_mb": 0.05
    },
    {
      "name": "15.avif",
      "local": "img/15.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109034/iloveyou/images/15.avif",
      "bytes": 34755,
      "size_mb": 0.03
    },
    {
      "name": "16.avif",
      "local": "img/16.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109047/iloveyou/images/16.avif",
      "bytes": 78172,
      "size_mb": 0.07
    },
    {
      "name": "17.avif",
      "local": "img/17.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109051/iloveyou/images/17.avif",
      "bytes": 29704,
      "size_mb": 0.03
    },
    {
      "name": "18.avif",
      "local": "img/18.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109064/iloveyou/images/18.avif",
      "bytes": 81006,
      "size_mb": 0.08
    },
    {
      "name": "19.avif",
      "local": "img/19.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109078/iloveyou/images/19.avif",
      "bytes": 80338,
      "size_mb": 0.08
    },
    {
      "name": "2.avif",
      "local": "img/2.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109082/iloveyou/images/2.avif",
      "bytes": 40836,
      "size_mb": 0.04
    },
    {
      "name": "20.avif",
      "local": "img/20.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109094/iloveyou/images/20.avif",
      "bytes": 55769,
      "size_mb": 0.05
    },
    {
      "name": "21.avif",
      "local": "img/21.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109105/iloveyou/images/21.avif",
      "bytes": 51277,
      "size_mb": 0.05
    },
    {
      "name": "22.avif",
      "local": "img/22.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109116/iloveyou/images/22.avif",
      "bytes": 42470,
      "size_mb": 0.04
    },
    {
      "name": "23.avif",
      "local": "img/23.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109127/iloveyou/images/23.avif",
      "bytes": 44004,
      "size_mb": 0.04
    },
    {
      "name": "24.avif",
      "local": "img/24.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109137/iloveyou/images/24.avif",
      "bytes": 41372,
      "size_mb": 0.04
    },
    {
      "name": "25.avif",
      "local": "img/25.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109147/iloveyou/images/25.avif",
      "bytes": 42890,
      "size_mb": 0.04
    },
    {
      "name": "26.avif",
      "local": "img/26.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109158/iloveyou/images/26.avif",
      "bytes": 98050,
      "size_mb": 0.09
    },
    {
      "name": "27.avif",
      "local": "img/27.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109173/iloveyou/images/27.avif",
      "bytes": 86798,
      "size_mb": 0.08
    },
    {
      "name": "28.avif",
      "local": "img/28.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109186/iloveyou/images/28.avif",
      "bytes": 162698,
      "size_mb": 0.16
    },
    {
      "name": "29.avif",
      "local": "img/29.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109190/iloveyou/images/29.avif",
      "bytes": 35032,
      "size_mb": 0.03
    },
    {
      "name": "3.avif",
      "local": "img/3.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109195/iloveyou/images/3.avif",
      "bytes": 40384,
      "size_mb": 0.04
    },
    {
      "name": "30.avif",
      "local": "img/30.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109199/iloveyou/images/30.avif",
      "bytes": 34316,
      "size_mb": 0.03
    },
    {
      "name": "31.avif",
      "local": "img/31.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109203/iloveyou/images/31.avif",
      "bytes": 34280,
      "size_mb": 0.03
    },
    {
      "name": "32.avif",
      "local": "img/32.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109207/iloveyou/images/32.avif",
      "bytes": 32230,
      "size_mb": 0.03
    },
    {
      "name": "33.avif",
      "local": "img/33.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109211/iloveyou/images/33.avif",
      "bytes": 34851,
      "size_mb": 0.03
    },
    {
      "name": "34.avif",
      "local": "img/34.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109215/iloveyou/images/34.avif",
      "bytes": 35548,
      "size_mb": 0.03
    },
    {
      "name": "35.avif",
      "local": "img/35.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109219/iloveyou/images/35.avif",
      "bytes": 34355,
      "size_mb": 0.03
    },
    {
      "name": "36.avif",
      "local": "img/36.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109223/iloveyou/images/36.avif",
      "bytes": 41821,
      "size_mb": 0.04
    },
    {
      "name": "37.avif",
      "local": "img/37.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109227/iloveyou/images/37.avif",
      "bytes": 43642,
      "size_mb": 0.04
    },
    {
      "name": "38.avif",
      "local": "img/38.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109240/iloveyou/images/38.avif",
      "bytes": 147772,
      "size_mb": 0.14
    },
    {
      "name": "39.avif",
      "local": "img/39.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109253/iloveyou/images/39.avif",
      "bytes": 156342,
      "size_mb": 0.15
    },
    {
      "name": "4.avif",
      "local": "img/4.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109257/iloveyou/images/4.avif",
      "bytes": 38836,
      "size_mb": 0.04
    },
    {
      "name": "40.avif",
      "local": "img/40.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109269/iloveyou/images/40.avif",
      "bytes": 149018,
      "size_mb": 0.14
    },
    {
      "name": "41.avif",
      "local": "img/41.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109282/iloveyou/images/41.avif",
      "bytes": 145474,
      "size_mb": 0.14
    },
    {
      "name": "42.avif",
      "local": "img/42.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109297/iloveyou/images/42.avif",
      "bytes": 127437,
      "size_mb": 0.12
    },
    {
      "name": "43.avif",
      "local": "img/43.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109314/iloveyou/images/43.avif",
      "bytes": 156319,
      "size_mb": 0.15
    },
    {
      "name": "44.avif",
      "local": "img/44.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109329/iloveyou/images/44.avif",
      "bytes": 183270,
      "size_mb": 0.17
    },
    {
      "name": "45.avif",
      "local": "img/45.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109342/iloveyou/images/45.avif",
      "bytes": 187669,
      "size_mb": 0.18
    },
    {
      "name": "46.avif",
      "local": "img/46.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109356/iloveyou/images/46.avif",
      "bytes": 187669,
      "size_mb": 0.18
    },
    {
      "name": "47.avif",
      "local": "img/47.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109369/iloveyou/images/47.avif",
      "bytes": 176024,
      "size_mb": 0.17
    },
    {
      "name": "48.avif",
      "local": "img/48.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109382/iloveyou/images/48.avif",
      "bytes": 185709,
      "size_mb": 0.18
    },
    {
      "name": "49.avif",
      "local": "img/49.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109395/iloveyou/images/49.avif",
      "bytes": 141483,
      "size_mb": 0.13
    },
    {
      "name": "5.avif",
      "local": "img/5.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109399/iloveyou/images/5.avif",
      "bytes": 35402,
      "size_mb": 0.03
    },
    {
      "name": "50.avif",
      "local": "img/50.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109413/iloveyou/images/50.avif",
      "bytes": 142815,
      "size_mb": 0.14
    },
    {
      "name": "51.avif",
      "local": "img/51.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109425/iloveyou/images/51.avif",
      "bytes": 132190,
      "size_mb": 0.13
    },
    {
      "name": "52.avif",
      "local": "img/52.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109438/iloveyou/images/52.avif",
      "bytes": 138522,
      "size_mb": 0.13
    },
    {
      "name": "53.avif",
      "local": "img/53.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109452/iloveyou/images/53.avif",
      "bytes": 159626,
      "size_mb": 0.15
    },
    {
      "name": "54.avif",
      "local": "img/54.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109465/iloveyou/images/54.avif",
      "bytes": 161114,
      "size_mb": 0.15
    },
    {
      "name": "55.avif",
      "local": "img/55.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109477/iloveyou/images/55.avif",
      "bytes": 93971,
      "size_mb": 0.09
    },
    {
      "name": "56.avif",
      "local": "img/56.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109502/iloveyou/images/56.avif",
      "bytes": 133247,
      "size_mb": 0.13
    },
    {
      "name": "57.avif",
      "local": "img/57.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109511/iloveyou/images/57.avif",
      "bytes": 12643,
      "size_mb": 0.01
    },
    {
      "name": "58.avif",
      "local": "img/58.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109517/iloveyou/images/58.avif",
      "bytes": 24811,
      "size_mb": 0.02
    },
    {
      "name": "59.avif",
      "local": "img/59.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109543/iloveyou/images/59.avif",
      "bytes": 81006,
      "size_mb": 0.08
    },
    {
      "name": "6.avif",
      "local": "img/6.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109547/iloveyou/images/6.avif",
      "bytes": 28454,
      "size_mb": 0.03
    },
    {
      "name": "60.avif",
      "local": "img/60.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109552/iloveyou/images/60.avif",
      "bytes": 42923,
      "size_mb": 0.04
    },
    {
      "name": "61.avif",
      "local": "img/61.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109557/iloveyou/images/61.avif",
      "bytes": 42923,
      "size_mb": 0.04
    },
    {
      "name": "62.avif",
      "local": "img/62.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109561/iloveyou/images/62.avif",
      "bytes": 40836,
      "size_mb": 0.04
    },
    {
      "name": "63.avif",
      "local": "img/63.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109566/iloveyou/images/63.avif",
      "bytes": 40384,
      "size_mb": 0.04
    },
    {
      "name": "64.avif",
      "local": "img/64.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109579/iloveyou/images/64.avif",
      "bytes": 164852,
      "size_mb": 0.16
    },
    {
      "name": "65.avif",
      "local": "img/65.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109592/iloveyou/images/65.avif",
      "bytes": 141483,
      "size_mb": 0.13
    },
    {
      "name": "66.avif",
      "local": "img/66.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109603/iloveyou/images/66.avif",
      "bytes": 86997,
      "size_mb": 0.08
    },
    {
      "name": "67.avif",
      "local": "img/67.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109614/iloveyou/images/67.avif",
      "bytes": 79275,
      "size_mb": 0.08
    },
    {
      "name": "68.avif",
      "local": "img/68.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109623/iloveyou/images/68.avif",
      "bytes": 65750,
      "size_mb": 0.06
    },
    {
      "name": "69.avif",
      "local": "img/69.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109633/iloveyou/images/69.avif",
      "bytes": 62495,
      "size_mb": 0.06
    },
    {
      "name": "7.avif",
      "local": "img/7.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109638/iloveyou/images/7.avif",
      "bytes": 45034,
      "size_mb": 0.04
    },
    {
      "name": "70.avif",
      "local": "img/70.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109644/iloveyou/images/70.avif",
      "bytes": 34576,
      "size_mb": 0.03
    },
    {
      "name": "71.avif",
      "local": "img/71.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109649/iloveyou/images/71.avif",
      "bytes": 29350,
      "size_mb": 0.03
    },
    {
      "name": "72.avif",
      "local": "img/72.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109656/iloveyou/images/72.avif",
      "bytes": 56717,
      "size_mb": 0.05
    },
    {
      "name": "73.avif",
      "local": "img/73.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109664/iloveyou/images/73.avif",
      "bytes": 65617,
      "size_mb": 0.06
    },
    {
      "name": "74.avif",
      "local": "img/74.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109672/iloveyou/images/74.avif",
      "bytes": 59363,
      "size_mb": 0.06
    },
    {
      "name": "75.avif",
      "local": "img/75.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109681/iloveyou/images/75.avif",
      "bytes": 64403,
      "size_mb": 0.06
    },
    {
      "name": "76.avif",
      "local": "img/76.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109688/iloveyou/images/76.avif",
      "bytes": 42068,
      "size_mb": 0.04
    },
    {
      "name": "77.avif",
      "local": "img/77.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109694/iloveyou/images/77.avif",
      "bytes": 39723,
      "size_mb": 0.04
    },
    {
      "name": "78.avif",
      "local": "img/78.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109705/iloveyou/images/78.avif",
      "bytes": 82761,
      "size_mb": 0.08
    },
    {
      "name": "79.avif",
      "local": "img/79.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109710/iloveyou/images/79.avif",
      "bytes": 31236,
      "size_mb": 0.03
    },
    {
      "name": "8.avif",
      "local": "img/8.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109714/iloveyou/images/8.avif",
      "bytes": 36217,
      "size_mb": 0.03
    },
    {
      "name": "80.avif",
      "local": "img/80.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109722/iloveyou/images/80.avif",
      "bytes": 58028,
      "size_mb": 0.06
    },
    {
      "name": "81.avif",
      "local": "img/81.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109728/iloveyou/images/81.avif",
      "bytes": 51329,
      "size_mb": 0.05
    },
    {
      "name": "82.avif",
      "local": "img/82.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109733/iloveyou/images/82.avif",
      "bytes": 24424,
      "size_mb": 0.02
    },
    {
      "name": "83.avif",
      "local": "img/83.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109737/iloveyou/images/83.avif",
      "bytes": 16528,
      "size_mb": 0.02
    },
    {
      "name": "84.avif",
      "local": "img/84.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109746/iloveyou/images/84.avif",
      "bytes": 79272,
      "size_mb": 0.08
    },
    {
      "name": "85.avif",
      "local": "img/85.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109753/iloveyou/images/85.avif",
      "bytes": 53864,
      "size_mb": 0.05
    },
    {
      "name": "86.avif",
      "local": "img/86.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109761/iloveyou/images/86.avif",
      "bytes": 39135,
      "size_mb": 0.04
    },
    {
      "name": "87.avif",
      "local": "img/87.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109768/iloveyou/images/87.avif",
      "bytes": 41304,
      "size_mb": 0.04
    },
    {
      "name": "88.avif",
      "local": "img/88.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109776/iloveyou/images/88.avif",
      "bytes": 56742,
      "size_mb": 0.05
    },
    {
      "name": "89.avif",
      "local": "img/89.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109784/iloveyou/images/89.avif",
      "bytes": 52826,
      "size_mb": 0.05
    },
    {
      "name": "9.avif",
      "local": "img/9.avif",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109788/iloveyou/images/9.avif",
      "bytes": 34907,
      "size_mb": 0.03
    },
    {
      "name": "90.avif",
      "local": "img/90.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109796/iloveyou/images/90.avif",
      "bytes": 58419,
      "size_mb": 0.06
    },
    {
      "name": "91.avif",
      "local": "img/91.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109804/iloveyou/images/91.avif",
      "bytes": 53271,
      "size_mb": 0.05
    },
    {
      "name": "92.avif",
      "local": "img/92.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109811/iloveyou/images/92.avif",
      "bytes": 58122,
      "size_mb": 0.06
    },
    {
      "name": "93.avif",
      "local": "img/93.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109818/iloveyou/images/93.avif",
      "bytes": 49762,
      "size_mb": 0.05
    },
    {
      "name": "94.avif",
      "local": "img/94.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109825/iloveyou/images/94.avif",
      "bytes": 48364,
      "size_mb": 0.05
    },
    {
      "name": "95.avif",
      "local": "img/95.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109833/iloveyou/images/95.avif",
      "bytes": 53142,
      "size_mb": 0.05
    },
    {
      "name": "96.avif",
      "local": "img/96.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109839/iloveyou/images/96.avif",
      "bytes": 44753,
      "size_mb": 0.04
    },
    {
      "name": "97.avif",
      "local": "img/97.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109846/iloveyou/images/97.avif",
      "bytes": 40581,
      "size_mb": 0.04
    },
    {
      "name": "98.avif",
      "local": "img/98.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109854/iloveyou/images/98.avif",
      "bytes": 42541,
      "size_mb": 0.04
    },
    {
      "name": "99.avif",
      "local": "img/99.JPG",
      "url": "https://res.cloudinary.com/dtoaci0hp/image/upload/v1772109860/iloveyou/images/99.avif",
      "bytes": 32629,
      "size_mb": 0.03
    }
  ],
  "videos": [
    {
      "ok": true,
      "name": "1.mp4",
      "local": "video/1.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772104533/iloveyou/videos/1.mp4",
      "bytes": 3392141,
      "size_mb": 3.23,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "10.mp4",
      "local": "video/10.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110083/iloveyou/videos/10.mp4",
      "bytes": 8721770,
      "size_mb": 8.32,
      "stage": "stage1_720p_30fps"
    },
    {
      "ok": true,
      "name": "11.mp4",
      "local": "video/11.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110101/iloveyou/videos/11.mp4",
      "bytes": 4352755,
      "size_mb": 4.15,
      "stage": "stage1_720p_30fps"
    },
    {
      "ok": true,
      "name": "12.mp4",
      "local": "video/12.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110104/iloveyou/videos/12.mp4",
      "bytes": 1544572,
      "size_mb": 1.47,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "13.mp4",
      "local": "video/13.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110111/iloveyou/videos/13.mp4",
      "bytes": 3244714,
      "size_mb": 3.09,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "14.mp4",
      "local": "video/14.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110114/iloveyou/videos/14.mp4",
      "bytes": 245777,
      "size_mb": 0.23,
      "stage": "stage1_720p_30fps"
    },
    {
      "ok": true,
      "name": "15.mp4",
      "local": "video/15.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110126/iloveyou/videos/15.mp4",
      "bytes": 1584597,
      "size_mb": 1.51,
      "stage": "stage1_720p_30fps"
    },
    {
      "ok": true,
      "name": "16.mp4",
      "local": "video/16.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110132/iloveyou/videos/16.mov",
      "bytes": 2841846,
      "size_mb": 2.71,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "17.mp4",
      "local": "video/17.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110149/iloveyou/videos/17.mp4",
      "bytes": 3293535,
      "size_mb": 3.14,
      "stage": "stage1_720p_30fps"
    },
    {
      "ok": true,
      "name": "18.mp4",
      "local": "video/18.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110512/iloveyou/videos/18.mp4",
      "bytes": 4432027,
      "size_mb": 4.23,
      "stage": "stage2_540p_30fps"
    },
    {
      "ok": true,
      "name": "19.mp4",
      "local": "video/19.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110530/iloveyou/videos/19.mp4",
      "bytes": 4195566,
      "size_mb": 4,
      "stage": "stage1_720p_30fps"
    },
    {
      "ok": true,
      "name": "2.mp4",
      "local": "video/2.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110536/iloveyou/videos/2.mp4",
      "bytes": 2156893,
      "size_mb": 2.06,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "20.mp4",
      "local": "video/20.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110549/iloveyou/videos/20.mov",
      "bytes": 6463099,
      "size_mb": 6.16,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "21.mp4",
      "local": "video/21.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110586/iloveyou/videos/21.mp4",
      "bytes": 4227777,
      "size_mb": 4.03,
      "stage": "stage2_540p_30fps"
    },
    {
      "ok": true,
      "name": "22.mp4",
      "local": "video/22.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110590/iloveyou/videos/22.mp4",
      "bytes": 728207,
      "size_mb": 0.69,
      "stage": "stage1_720p_30fps"
    },
    {
      "ok": true,
      "name": "23.mp4",
      "local": "video/23.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110599/iloveyou/videos/23.mp4",
      "bytes": 2296525,
      "size_mb": 2.19,
      "stage": "stage1_720p_30fps"
    },
    {
      "ok": true,
      "name": "24.mp4",
      "local": "video/24.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110624/iloveyou/videos/24.mp4",
      "bytes": 6475169,
      "size_mb": 6.18,
      "stage": "stage1_720p_30fps"
    },
    {
      "ok": true,
      "name": "25.mp4",
      "local": "video/25.MOV",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110657/iloveyou/videos/25.mp4",
      "bytes": 9958817,
      "size_mb": 9.5,
      "stage": "stage1_720p_30fps"
    },
    {
      "ok": true,
      "name": "3.mp4",
      "local": "video/3.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110660/iloveyou/videos/3.mp4",
      "bytes": 692631,
      "size_mb": 0.66,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "4.mp4",
      "local": "video/4.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110664/iloveyou/videos/4.mp4",
      "bytes": 1634408,
      "size_mb": 1.56,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "5.mp4",
      "local": "video/5.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110672/iloveyou/videos/5.mp4",
      "bytes": 3580767,
      "size_mb": 3.41,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "6.mp4",
      "local": "video/6.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110677/iloveyou/videos/6.mp4",
      "bytes": 1553910,
      "size_mb": 1.48,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "7.mp4",
      "local": "video/7.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110683/iloveyou/videos/7.mp4",
      "bytes": 1659024,
      "size_mb": 1.58,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "8.mp4",
      "local": "video/8.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110697/iloveyou/videos/8.mp4",
      "bytes": 2166377,
      "size_mb": 2.07,
      "stage": "compressed"
    },
    {
      "ok": true,
      "name": "9.mp4",
      "local": "video/9.mp4",
      "url": "https://res.cloudinary.com/dtoaci0hp/video/upload/v1772110711/iloveyou/videos/9.mp4",
      "bytes": 5025382,
      "size_mb": 4.79,
      "stage": "compressed"
    }
  ],
  "failed_images": [],
  "failed_videos": []
};
